version: '2.0'
services:
  web:
    restart: "no"
    build: .
    ports:
      - "8020:8000"
    volumes:
      - .:/movie_graph/
    depends_on:
      - database
    environment:
      - DATABASE_URL=bolt://neo4j:foobar@database:7687
    entrypoint: ./wait-for-database.sh database
    command: gunicorn --reload -b 0.0.0.0:8000 movie_graph.app

  database:
    restart: "no"
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/foobar
    ports:
    - "7473:7473"
    - "7474:7474"
    - "7687:7687"

  tests:
    restart: "no"
    build: .
    volumes:
      - .:/movie_graph/
    depends_on:
      - test-database
    environment:
      - DATABASE_URL=bolt://neo4j:foobar@test-database:7687
    entrypoint: ./wait-for-database.sh test-database
    command: pytest

  test-database:
    restart: "no"
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/foobar
    ports:
    - "7473:7473"
    - "7474:7474"
    - "7687:7687"


volumes:
  data:
    driver: local
  storage:
    driver: local
